version: '2'

services:

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: spring-data-rest
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password